server:
  port: ${USER-SERVICE-PORT:3000}

spring:
  application:
    name: USER-SERVICE
  main:
    banner-mode: off
  jackson:
    default-property-inclusion: non_null
  config:
    import: classpath:db-config.yaml, security-config.yaml

communicationms.base-url: ${COMMUNICATION-SERVICE-BASE-URL:http://localhost:3001}

users:
  default-roles:
    - USER_MS_USER

app:
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:8080}
  verification-email:
    expiration-minutes: 1440
  password-reset:
    expiration-minutes: 1440
